// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDi17k_-_5eM9Ns-RFidXXZEtI1qtWA_FY',
    appId: '1:446231829823:web:cb9e826b81738ff354478a',
    messagingSenderId: '446231829823',
    projectId: 'aptimaster-384af',
    authDomain: 'aptimaster-384af.firebaseapp.com',
    storageBucket: 'aptimaster-384af.firebasestorage.app',
    measurementId: 'G-XF81WPF1P5',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBZLcQNKnVhJHKCLcaBBvHIhKsa4diTR3c',
    appId: '1:446231829823:android:3d6c4ea0ee037aa354478a',
    messagingSenderId: '446231829823',
    projectId: 'aptimaster-384af',
    storageBucket: 'aptimaster-384af.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDaEcjBjUjNBMP6X0DWkkARnhxNPPp6Frs',
    appId: '1:446231829823:ios:1819f3d4df3f4ba354478a',
    messagingSenderId: '446231829823',
    projectId: 'aptimaster-384af',
    storageBucket: 'aptimaster-384af.firebasestorage.app',
    iosBundleId: 'com.dhigrowth.aptimaster',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDaEcjBjUjNBMP6X0DWkkARnhxNPPp6Frs',
    appId: '1:446231829823:ios:e65908f9e621d31e54478a',
    messagingSenderId: '446231829823',
    projectId: 'aptimaster-384af',
    storageBucket: 'aptimaster-384af.firebasestorage.app',
    iosBundleId: 'com.dhigrowth.aptimaster',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDi17k_-_5eM9Ns-RFidXXZEtI1qtWA_FY',
    appId: '1:446231829823:web:2017e191585a804c54478a',
    messagingSenderId: '446231829823',
    projectId: 'aptimaster-384af',
    authDomain: 'aptimaster-384af.firebaseapp.com',
    storageBucket: 'aptimaster-384af.firebasestorage.app',
    measurementId: 'G-LGGBEWBLVG',
  );
}
